language: c
sudo: false

addons:
  apt:
    packages:
    - bison
    - flex
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - texinfo
    - grub-pc-bin
    - xorriso

cache:
  directories:
  - $HOME/inlow-toolchain

before_install:
- unset CC CXX
- export PATH="$HOME/inlow-toolchain/bin:$PATH"
install: make install-toolchain
script: make

notifications:
  email:
    - qjp5555@gmail.com
